name: Create Release on Tag

on:
  push:
    tags:
      - "20[0-9][0-9]-[0-1][0-9]-[0-3][0-9](.[0-9]+)?" # Matches YYYY-MM-DD or YYYY-MM-DD.patch

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get full commit history

      - name: Get previous tag
        id: previous-tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
          echo "prev_tag=${PREV_TAG}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Generate changelog with proper line breaks
          if [ -z "${{ steps.previous-tag.outputs.prev_tag }}" ]; then
            LOG=$(git log --pretty=format:"- %s%n")
          else
            LOG=$(git log --pretty=format:"- %s%n" ${{ steps.previous-tag.outputs.prev_tag }}..${{ github.ref_name }})
          fi
          # Escape special characters but preserve newlines
          LOG_ESCAPED=$(echo "$LOG" | sed 's/"/\\"/g')
          # Multiline output using environment file
          DELIMITER=$(openssl rand -hex 16)
          echo "changelog<<${DELIMITER}" >> $GITHUB_ENV
          echo "$LOG_ESCAPED" >> $GITHUB_ENV
          echo "${DELIMITER}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ### Changelog

            *Automatically generated from commit messages since ${{ steps.previous-tag.outputs.prev_tag || 'the beginning' }}*

            ${{ env.changelog }}

          files: |
            removeFacebookSpam.user.js
