name: Create Release on Tag

on:
  push:
    tags:
      - "20[0-9][0-9]-[0-1][0-9]-[0-3][0-9]" # Matches date-like tags (YYYY-MM-DD)

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get full commit history

      - name: Get previous tag
        id: previous-tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
          echo "prev_tag=${PREV_TAG}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Escape special characters and convert to single line
          if [ -z "${{ steps.previous-tag.outputs.prev_tag }}" ]; then
            LOG=$(git log --pretty=format:"- %s" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/"/\\"/g')
          else
            LOG=$(git log --pretty=format:"- %s" ${{ steps.previous-tag.outputs.prev_tag }}..${{ github.ref_name }} | sed ':a;N;$!ba;s/\n/ /g' | sed 's/"/\\"/g')
          fi
          # Use environment file to handle multiline output
          echo "changelog<<EOF" >> $GITHUB_ENV
          echo "$LOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          CHANGELOG: ${{ env.changelog }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ### Changelog

            *Automatically generated from commit messages since ${{ steps.previous-tag.outputs.prev_tag || 'the beginning' }}*

            ${{ env.changelog }}
          files: |
            removeFacebookSpam.user.js
